### ISSUE TITLE
Release can-util and strict changes

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-make-rest#28]
It looks like the can-util removal and "use strict" changes were never released: https://github.com/canjs/can-make-rest/compare/v0.1.3...master

Can we release this as a 1.0? It looks like can-connect is the only package that depends on this package and it’s been using `<2.0.0` as its semver range since the v3 prereleases: https://github.com/canjs/can-connect/commit/a9b80242f27d6e128ba05984ceef321f25415c58

**Comment by phillipskevin** [comment]
Any idea why this wasn't released?

**Comment by chasenlehara** [comment]
No idea, probably just a mistake

**Comment by phillipskevin** [comment]
Ok. Let's release a `1.0.0-pre.0` and update canjs#major with it then.

**Comment by phillipskevin** [comment]
@cherifGsoul is this done?

**Comment by cherifGsoul** [comment]
@phillipskevin Yes it released https://github.com/canjs/can-make-rest/releases/tag/v1.0.0-pre.0
